// export const  cardsMock= [
//     {
//       id:1,
//       name: 'Apple Watch Series 7',
//       price: 299,
//       descripcion:"El Apple Watch Series 7 es un reloj inteligente con una pantalla más grande y funciones avanzadas de seguimiento de salud.",
//       stock: 10,
//       image: 'https://www.apple.com/newsroom/images/product/watch/standard/Apple_watch-series7-availability_hero_10052021_big.jpg.large.jpg',
//       categoryId: 1,
//     },
//     {
//       id:2,
//       name: 'iPhone 13',
//       price: 699,
//       descripcion:"El iPhone 13 es el último teléfono inteligente de Apple con una potente cámara y un rendimiento excepcional.",
//       stock: 5,
//       image: 'https://allstore.com.ve/wp-content/uploads/2022/01/768-iPhone_13_Pink-1.png',
//       categoryId: 2,
//     },
//     {
//       id:3,
//       name: 'MacBook Pro',
//       price: 899,
//       descripcion:" El MacBook Pro es una potente computadora portátil diseñada para profesionales creativos y usuarios exigentes.",
//       stock: 3,
//       image: 'https://media.cnn.com/api/v1/images/stellar/prod/230125131405-macbook-pro-14-inch-2023-review-cnnu-7.jpg?c=16x9&q=h_653,w_1160,c_fill/f_webp',
//       categoryId: 3,
//     },
//     {
//         id:4,
//         name: 'Rtx 3050ti',
//         price: 150,
//         descripcion:"Tarjeta gráfica Rtx 3050ti para juegos y aplicaciones de alto rendimiento.",
//         stock: 3,
//         image: 'https://m.media-amazon.com/images/I/71Qa+vAazvL._AC_SL1500_.jpg',
//         categoryId: 3,
//       },
//       {
//         id:5,
//         name: 'Logitech g502',
//         price: 19,
//         descripcion:"Ratón Logitech g502 con sensor de alta precisión y botones programables.",
//         stock: 3,
//         image: 'https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_SL1500_.jpg',
//         categoryId: 3,
//       },
//       {
//         id:6,
//         name: 'Teclado RoyalKludge',
//         price: 25,
//         descripcion:"Teclado mecánico RoyalKludge con retroiluminación RGB y diseño compacto.",
//         stock: 3,
//         image: 'https://m.media-amazon.com/images/I/61nghmq8GPL._AC_SL1500_.jpg',
//         categoryId: 3,
//       },
//       {
//         id:7,
//         name: 'Tecla Gigante Enter',
//         price: 3,
//         descripcion:"Tecla Gigante Enter para agregar diversión a tu teclado.",
//         stock: 3,
//         image: 'https://m.media-amazon.com/images/I/61jCGWTu-mL._AC_SL1017_.jpg',
//         categoryId: 3,
//       },
//       {
//         id:8,
//         name: 'COSORI Olla Presion Electrica',
//         price: 40,
//         descripcion:"Olla de presión eléctrica COSORI para cocinar de manera rápida y eficiente.",
//         stock: 3,
//         image: 'https://m.media-amazon.com/images/I/71q-GYnJW9L._AC_SL1500_.jpg',
//         categoryId: 3,
//       }
    
//   ];

 